### ISSUE TITLE
Map stays blank if user has no permissions on default theme

### ISSUE THREAD

**Issue by olivierdalang** [qwc-services/qwc-map-viewer#12]
Hey ! Not 100% this is the right repo to report this issue...

In our setup, there is no default theme that every user has access to (we run qwc-map-viewer with `AUTH_REQUIRED: "true"`). This leads to the map staying blank on startup for all users except for the user that happens to have access to the first theme.

In such case, it would be better to fall back to the first project that user has access to.

See `themes.json` below, as served by qwc-map-viewer below, where you can see that the default theme isn't listed in the available themes. Note that the input configuration is generated by the config generator, which seems to assume the first project as default (never specified that manually). Arguably the config generator shouldn't add the "defaultTheme" property, and QWC should use the first theme if no "defaultTheme" is set.

Thanks !!

```json
{
  "themes": {
    ...
    "defaultTheme": "scan/client_a",
    ...
    "items": [
      {
        ...
        "id": "scan/client_b",
        ...
      }
    ],
    ...
  }
}
```

**Comment by manisandro** [comment]
I'd say setting a default theme which is protected will always lead to undesired results. For authenticated users, the default startup params can be stored in the QWC Config DB (`qwc_config.user_infos -> default_url_params`). I'd suggest using that approach instead.
