### ISSUE TITLE
Setting up tenants

### ISSUE THREAD

**Issue by NullSeile** [qwc-services/qwc-map-viewer#14]
We are trying to set up qwc2 with tenants. We tried the following setup: /map/<tenant-name> which sets up the `QWC_TENANT` environment variable. This works fine with the default tenant, but it does a wrong redirect with every other one (i.e.: `/map/<tenant-name>` redirects to `/<tenant-name>/map/<tenant-name>`).

We noticed that this behavior is caused by the class `TenantPrefixMiddleware`. 

We could use some help on how to set up tenants with this service and others like admin-gui which also has this behavior.

Thank you!

**Comment by tpo** [comment]
Please contact info@sourcepole.ch in case you need commercial support
