### ISSUE TITLE
Missing parameters in URL when authentication is necessary

### ISSUE THREAD

**Issue by MarkusAlbrechtSWM** [qwc-services/qwc-map-viewer#21]
When calling QWC2 with start parameters in the URL, the parameters get lost if authentication is required.

For example, if QWC2 is called with the following start parameters:
```
https://qwc2-host/?c=688091.313644,5338424.983487&crs=EPSG:25832&s=500&l=Layer1,Layer2&hc=true
```
and authentication is required, a redirect to the following URL is sent:
```
https://qwc2-host/login?url=https://qwc2-host/?c=688091.313644,5338424.983487&crs=EPSG:25832&s=500&l=Layer1,Layer2&hc=true
```
Unpacking the URL in the qwc-oidc-auth-Module with `target_url = request.args.get('url', tenant_base())` leads to the loss of all parameters except one.

The cause of this problem is a missing URL encoding in the qwc-map-viewer's `server.py` at [Line 80](https://github.com/qwc-services/qwc-map-viewer/blob/310d1217e9f5b27ce5ec98dc9073f095c7ed32b4/src/server.py#L80).

#### Suggested Fix
I suggest encoding `request.url` with urllib's `urllib.parse.quote(request.url)` to address this issue.

**Comment by manisandro** [comment]
Sorry for the late reply, missed the issue. Thanks for the report, fixed in https://github.com/qwc-services/qwc-map-viewer/commit/c42b7d1f17c10a91cbf3004c12cc400b131dbe33
