### ISSUE TITLE
example using qwc-fulltext-search-service in qwc-map-viewer

### ISSUE THREAD

**Issue by kahermann** [qwc-services/qwc-map-viewer#8]
qwc-services /qwc-map-viewer provides QWC2 Web Client application using QWC services
In mapViewerConfig.json there is a reference to the search service
 "#search_service_url": "/api/v2/search/fts/"
but there is no example for the using of his service

**Comment by manisandro** [comment]
qwc-docker has a demo setup of qwc-fulltext-search-service.
