### ISSUE TITLE
WMS 1.3.0 flip coordinate order for bbox request

### ISSUE THREAD

**Issue by kahermann** [qwc-services/qwc-map-viewer#9]
WMS 1.3.0 EPSG:31254 Request does not work:
http://vogis.cnv.at/mapserver/mapserv?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=schummerung_50cm_surface&STYLES=default&SRS=EPSG%3A31254&CRS=EPSG%3A31254&TILED=false&DPI=96&MAP=i_hoehen_und_gelaende_r_wms.map&WIDTH=2292&HEIGHT=824&BBOX=-72417%2C252507.33333333334%2C-23903.000000000004%2C269948.6666666667

WMS 1.3.0 EPSG:31254 Request works:
http://vogis.cnv.at/mapserver/mapserv?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=schummerung_50cm_surface&STYLES=default&SRS=EPSG%3A31254&CRS=EPSG%3A31254&TILED=false&DPI=96&MAP=i_hoehen_und_gelaende_r_wms.map&WIDTH=2292&HEIGHT=824&BBOX=252507.33333333334%2C-72417%2C269948.6666666667%2C-23903.000000000004

**Comment by manisandro** [comment]
Should be since fixed.
